import { PrismaClient } from '../lib/generated/prisma';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Adding more products...');

  // Get category IDs
  const categories = await prisma.category.findMany();
  const categoryMap: Record<string, string> = {};
  categories.forEach(cat => { categoryMap[cat.slug] = cat.id; });

  // More Electronics
  const products = [
    // Gaming accessories
    { name: 'Logitech G Pro X Mouse', slug: 'logitech-g-pro-x-mouse', price: 79, originalPrice: 99, discount: 20, description: 'Ultra-lightweight esports mouse with HERO sensor.', images: JSON.stringify(['https://images.unsplash.com/photo-1527814050087-3793815479db?w=500']), specifications: JSON.stringify({ 'DPI': '25,600', 'Weight': '63g', 'Buttons': '8', 'Wireless': 'Lightspeed' }), rating: 4.7, reviewCount: 3210, inStock: true, stock: 150, seller: 'Logitech', categorySlug: 'gaming', featured: true, flashSale: true },
    { name: 'Razer DeathAdder V3 Pro', slug: 'razer-deathadder-v3-pro', price: 149, originalPrice: 179, discount: 17, description: 'Pro esports mouse with optical switches.', images: JSON.stringify(['https://images.unsplash.com/photo-1527814050087-3793815479db?w=500']), specifications: JSON.stringify({ 'DPI': '30,000', 'Weight': '64g', 'Switches': 'Optical Gen-3', 'Ergonomic': 'Yes' }), rating: 4.8, reviewCount: 1876, inStock: true, stock: 100, seller: 'Razer', categorySlug: 'gaming', featured: true, flashSale: true },
    { name: 'SteelSeries Apex Pro Keyboard', slug: 'steelseries-apex-pro', price: 179, originalPrice: 229, discount: 22, description: 'Mechanical keyboard with adjustable switches.', images: JSON.stringify(['https://images.unsplash.com/photo-1587829741301-dc798b91a603?w=500']), specifications: JSON.stringify({ 'Switches': 'OmniPoint 2.0', 'Size': 'Full', 'RGB': 'Per-key', 'OLED': 'Smart Display' }), rating: 4.7, reviewCount: 1234, inStock: true, stock: 80, seller: 'SteelSeries', categorySlug: 'gaming', featured: false, flashSale: true },
    { name: 'Corsair K70 RGB Pro', slug: 'corsair-k70-rgb-pro', price: 129, originalPrice: 169, discount: 24, description: 'Cherry MX mechanical gaming keyboard.', images: JSON.stringify(['https://images.unsplash.com/photo-1587829741301-dc798b91a603?w=500']), specifications: JSON.stringify({ 'Switches': 'Cherry MX Red', 'Size': 'Full', 'RGB': 'Per-key', 'Build': 'Aluminum' }), rating: 4.6, reviewCount: 2134, inStock: true, stock: 100, seller: 'Corsair', categorySlug: 'gaming', featured: false, flashSale: true },
    { name: 'Razer BlackShark V2 Pro', slug: 'razer-blackshark-v2-pro', price: 149, originalPrice: 179, discount: 17, description: 'Wireless esports headset with THX spatial audio.', images: JSON.stringify(['https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=500']), specifications: JSON.stringify({ 'Drivers': '50mm', 'Frequency': '12-28kHz', 'Mic': 'HyperClear', 'Wireless': 'Pro' }), rating: 4.7, reviewCount: 1876, inStock: true, stock: 100, seller: 'Razer', categorySlug: 'gaming', featured: true, flashSale: true },
    { name: 'SteelSeries Arctis 7+', slug: 'steelseries-arctis-7-plus', price: 169, originalPrice: 199, discount: 15, description: 'Wireless gaming headset with great battery life.', images: JSON.stringify(['https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=500']), specifications: JSON.stringify({ 'Drivers': '40mm', 'Battery': '30 hours', 'Wireless': '2.4GHz', 'Platform': 'Multi-platform' }), rating: 4.7, reviewCount: 1543, inStock: true, stock: 80, seller: 'SteelSeries', categorySlug: 'gaming', featured: false, flashSale: true },
    { name: 'Logitech G Cloud Handheld', slug: 'logitech-g-cloud', price: 349, originalPrice: 449, discount: 22, description: ' handheld cloud gaming device.', images: JSON.stringify(['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500']), specifications: JSON.stringify({ 'Screen': '7" LCD', 'Battery': '12+ hours', 'Cloud': 'Xbox/GeForce', 'Controllers': 'Removable' }), rating: 4.4, reviewCount: 543, inStock: true, stock: 30, seller: 'Logitech', categorySlug: 'gaming', featured: false, flashSale: false },
    { name: 'Razer Kishi V2', slug: 'razer-kishi-v2', price: 149, originalPrice: 179, discount: 17, description: 'Mobile gaming controller for phones.', images: JSON.stringify(['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500']), specifications: JSON.stringify({ 'Connect': 'USB-C', 'Pass-through': 'Charging', 'Latency': 'Low', 'Works': 'Android/iOS' }), rating: 4.5, reviewCount: 876, inStock: true, stock: 60, seller: 'Razer', categorySlug: 'gaming', featured: false, flashSale: true },
    { name: 'PlayStation DualSense Controller', slug: 'ps5-dualsense', price: 69, originalPrice: 79, discount: 13, description: 'PS5 controller with haptic feedback.', images: JSON.stringify(['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500']), specifications: JSON.stringify({ 'Haptics': 'Advanced', 'Triggers': 'Adaptive', 'Built-in': 'Mic', 'Speakers': 'Built-in' }), rating: 4.8, reviewCount: 5432, inStock: true, stock: 150, seller: 'Sony Gaming', categorySlug: 'gaming', featured: true, flashSale: true },
    { name: 'Xbox Wireless Controller', slug: 'xbox-wireless-controller', price: 59, originalPrice: 69, discount: 14, description: 'Xbox controller with share button.', images: JSON.stringify(['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500']), specifications: JSON.stringify({ 'Share': 'Button', 'Connect': 'Bluetooth', 'Compatible': 'Xbox/PC', '3.5mm': 'Jack' }), rating: 4.7, reviewCount: 4321, inStock: true, stock: 180, seller: 'Microsoft', categorySlug: 'gaming', featured: false, flashSale: true },
    { name: 'LG UltraGear 27" 144Hz', slug: 'lg-ultragear-27-144hz', price: 279, originalPrice: 349, discount: 20, description: 'Gaming monitor with 144Hz refresh rate.', images: JSON.stringify(['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500']), specifications: JSON.stringify({ 'Size': '27 inches', 'Resolution': '2560x1440', 'Refresh': '144Hz', 'Panel': 'IPS' }), rating: 4.6, reviewCount: 1234, inStock: true, stock: 40, seller: 'LG', categorySlug: 'gaming', featured: true, flashSale: true },
    { name: 'Samsung Odyssey G9', slug: 'samsung-odyssey-g9', price: 1099, originalPrice: 1499, discount: 27, description: '49" ultra-wide gaming monitor.', images: JSON.stringify(['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500']), specifications: JSON.stringify({ 'Size': '49 inches', 'Resolution': '5120x1440', 'Refresh': '240Hz', 'Curve': '1000R' }), rating: 4.8, reviewCount: 432, inStock: true, stock: 15, seller: 'Samsung', categorySlug: 'gaming', featured: false, flashSale: false },
    { name: 'Razer Core X eGPU', slug: 'razer-core-x', price: 699, externalPrice: 899, discount: 22, description: 'External GPU enclosure for laptops.', images: JSON.stringify(['https://images.unsplash.com/photo-1593642632823-8f7856677741?w=500']), specifications: JSON.stringify({ 'GPU': 'Up to 3-slot', 'Power': '500W', 'Thunderbolt': '3', 'RGB': 'Chroma' }), rating: 4.5, reviewCount: 321, inStock: true, stock: 20, seller: 'Razer', categorySlug: 'gaming', featured: false, flashSale: true },
    
    // More Fashion
    { name: "Levi's 511 Slim Fit Jeans", slug: 'levis-511-slim-fit', price: 55, originalPrice: 79, discount: 30, description: 'Modern slim fit jeans with stretch.', images: JSON.stringify(['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=500']), specifications: JSON.stringify({ 'Fit': 'Slim', 'Material': '99% Cotton 1% Elastane', 'Rise': 'Mid', 'Wash': 'Multiple' }), rating: 4.4, reviewCount: 4321, inStock: true, stock: 300, seller: "Levi's", categorySlug: 'fashion', featured: true, flashSale: true },
    { name: "Levi's 502 Taper Fit", slug: 'levis-502-taper', price: 55, originalPrice: 79, discount: 30, description: 'Comfortable taper fit jeans.', images: JSON.stringify(['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=500']), specifications: JSON.stringify({ 'Fit': 'Taper', 'Material': '99% Cotton 1% Elastane', 'Rise': 'Mid', 'Style': 'Comfort' }), rating: 4.4, reviewCount: 2876, inStock: true, stock: 250, seller: "Levi's", categorySlug: 'fashion', featured: false, flashSale: true },
    { name: "Dockers Classic Fit Pants", slug: 'dockers-classic-fit', price: 45, originalPrice: 65, discount: 31, description: 'Classic fit khaki pants.', images: JSON.stringify(['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500']), specifications: JSON.stringify({ 'Fit': 'Classic', 'Material': '100% Polyester', 'Waist': 'Classic', 'Sizes': '30-44' }), rating: 4.3, reviewCount: 1876, inStock: true, stock: 200, seller: 'Dockers', categorySlug: 'fashion', featured: false, flashSale: true },
    { name: "Carhartt Active Jacket", slug: 'carhartt-active-jacket', price: 79, originalPrice: 109, discount: 28, description: 'Warm and durable active jacket.', images: JSON.stringify(['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500']), specifications: JSON.stringify({ 'Material': 'Cotton Duck', 'Lining': 'Quilted', 'Sizes': 'S-XXL', 'Style': 'Work' }), rating: 4.6, reviewCount: 1234, inStock: true, stock: 100, seller: 'Carhartt', categorySlug: 'fashion', featured: false, flashSale: true },
    { name: 'Columbia Steens Mountain Fleece', slug: 'columbia-steens-mountain', price: 65, originalPrice: 95, discount: 32, description: 'Warm fleece jacket for outdoor.', images: JSON.stringify(['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500']), specifications: JSON.stringify({ 'Material': 'Fleece', 'Warmth': 'Light', 'Sizes': 'S-XXL', 'Activity': 'Outdoor' }), rating: 4.5, reviewCount: 876, inStock: true, stock: 120, seller: 'Columbia', categorySlug: 'fashion', featured: false, flashSale: true },
    { name: "The North Face Nuptse Jacket", slug: 'north-face-nuptse', price: 199, originalPrice: 279, discount: 29, description: 'Iconic puffer jacket with down fill.', images: JSON.stringify(['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500']), specifications: JSON.stringify({ 'Fill': '700-fill down', 'Waterproof': 'Yes', 'Sizes': 'S-XXL', 'Style': 'Puffer' }), rating: 4.7, reviewCount: 543, inStock: true, stock: 50, seller: 'The North Face', categorySlug: 'fashion', featured: true, flashSale: true },
    { name: 'Patagonia Better Sweater', slug: 'patagonia-better-sweater', price: 139, originalPrice: 179, discount: 22, description: 'Fleece sweater with recycled polyester.', images: JSON.stringify(['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500']), specifications: JSON.stringify({ 'Material': 'Recycled Polyester', 'Style': 'Sweater fleece', 'Sizes': 'XS-XXL', 'Eco': 'Yes' }), rating: 4.6, reviewCount: 654, inStock: true, stock: 80, seller: 'Patagonia', categorySlug: 'fashion', featured: false, flashSale: false },
    { name: 'Arc\'teryx Atom LT Hoody', slug: 'arcteryx-atom-lt', price: 199, originalPrice: 269, discount: 26, description: 'Lightweight insulated hoody.', images: JSON.stringify(['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500']), specifications: JSON.stringify({ 'Fill': 'Coreloft', 'Material': 'Tyono', 'Sizes': 'S-XXL', 'Activity': 'Alpine' }), rating: 4.8, reviewCount: 321, inStock: true, stock: 40, seller: 'Arc\'teryx', categorySlug: 'fashion', featured: false, flashSale: true },
    { name: 'Timberland Heritage Boots', slug: 'timberland-heritage-boots', price: 150, originalPrice: 190, discount: 21, description: 'Classic leather boots.', images: JSON.stringify(['https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=500']), specifications: JSON.stringify({ 'Material': 'Premium Leather', 'Waterproof': 'Timberland PRO', 'Sizes': '7-14', 'Style': 'Work/Casual' }), rating: 4.6, reviewCount: 876, inStock: true, stock: 80, seller: 'Timberland', categorySlug: 'fashion', featured: false, flashSale: true },
    { name: 'Clarks Desert Boots', slug: 'clarks-desert-boots', price: 100, originalPrice: 140, discount: 29, description: 'Classic desert boots with crepe sole.', images: JSON.stringify(['https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=500']), specifications: JSON.stringify({ 'Material': 'Suede or Leather', 'Sole': 'Crepe', 'Sizes': '6-13', 'Style': 'Classic' }), rating: 4.5, reviewCount: 1234, inStock: true, stock: 100, seller: 'Clarks', categorySlug: 'fashion', featured: false, flashSale: true },
    
    // More Home & Kitchen
    { name: 'Breville Bambino Plus', slug: 'breville-bambino-plus', price: 399, originalPrice: 499, discount: 20, description: 'Compact espresso machine with auto milk.', images: JSON.stringify(['https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500']), specifications: JSON.stringify({ 'Group': '54mm', 'Steam': 'Automatic', 'Heat-up': '3 seconds', 'Water': '64 oz' }), rating: 4.7, reviewCount: 1876, inStock: true, stock: 30, seller: 'Breville', categorySlug: 'home-kitchen', featured: true, flashSale: true },
    { name: 'Nespresso Creatista Plus', slug: 'nespresso-creatista-plus', price: 449, originalPrice: 599, discount: 25, description: 'Espresso machine with milk frother.', images: JSON.stringify(['https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500']), specifications: JSON.stringify({ 'Milk': 'Automatic frother', 'Brew': 'Espresso', 'Water': '60 oz', 'Settings': '8' }), rating: 4.6, reviewCount: 876, inStock: true, stock: 25, seller: 'Nespresso', categorySlug: 'home-kitchen', featured: false, flashSale: true },
    { name: 'Cuisinart Food Processor', slug: 'cuisinart-food-processor', price: 199, originalPrice: 279, discount: 29, description: '11-cup food processor with dough blade.', images: JSON.stringify(['https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=500']), specifications: JSON.stringify({ 'Capacity': '11 cups', 'Motor': '600W', 'Blades': 'Multiple', 'Bowl': 'Dishwasher safe' }), rating: 4.5, reviewCount: 1234, inStock: true, stock: 50, seller: 'Cuisinart', categorySlug: 'home-kitchen', featured: false, flashSale: true },
    { name: 'KitchenAid Artisan Mixer', slug: 'kitchenaid-artisan', price: 449, originalPrice: 549, discount: 18, description: '5-quart stand mixer with pouring shield.', images: JSON.stringify(['https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500']), specifications: JSON.stringify({ 'Capacity': '5 quarts', 'Motor': '325W', 'Speeds': '10', 'Colors': 'Multiple' }), rating: 4.9, reviewCount: 1876, inStock: true, stock: 30, seller: 'KitchenAid', categorySlug: 'home-kitchen', featured: true, flashSale: true },
    { name: 'Crock-Pot Express Crock', slug: 'crock-pot-express', price: 89, originalPrice: 119, discount: 25, description: 'Pressure cooker and slow cooker in one.', images: JSON.stringify(['https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=500']), specifications: JSON.stringify({ 'Capacity': '6 quart', 'Functions': '9', 'Programs': 'LCD', 'Includes': 'Recipe book' }), rating: 4.4, reviewCount: 1543, inStock: true, stock: 60, seller: 'Crock-Pot', categorySlug: 'home-kitchen', featured: false, flashSale: true },
    { name: 'Ninja Foodi Grill', slug: 'ninja-foodi-grill', price: 249, originalPrice: 329, discount: 24, description: 'Indoor grill with air fryer capability.', images: JSON.stringify(['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500']), specifications: JSON.stringify({ 'Grill': '6x faster', 'Capacity': '6 servings', 'Functions': '4', 'Cool-touch': 'Yes' }), rating: 4.5, reviewCount: 876, inStock: true, stock: 40, seller: 'Ninja', categorySlug: 'home-kitchen', featured: false, flashSale: true },
    { name: 'Shark Rotator Steam Mop', slug: 'shark-rotator-steam-mop', price: 99, originalPrice: 149, discount: 34, description: 'Steam mop with floor cleaning.', images: JSON.stringify(['https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500']), specifications: JSON.stringify({ 'Steam': 'Ready in 30 sec', 'Tank': 'Removable', 'Pads': 'Washable', 'Cords': '20 ft' }), rating: 4.4, reviewCount: 1876, inStock: true, stock: 50, seller: 'Shark', categorySlug: 'home-kitchen', featured: false, flashSale: true },
    { name: 'Bissell Pet Stain Eraser', slug: 'bissell-pet-stain-eraser', price: 149, originalPrice: 199, discount: 25, description: 'Cordless pet stain and odor remover.', images: JSON.stringify(['https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500']), specifications: JSON.stringify({ 'Tank': '32 oz', 'Cordless': 'Yes', 'Spray': 'Trigger', 'Tools': '3 pet tools' }), rating: 4.3, reviewCount: 2345, inStock: true, stock: 60, seller: 'Bissell', categorySlug: 'home-kitchen', featured: false, flashSale: false },
    { name: 'Ring Video Doorbell Pro 2', slug: 'ring-video-doorbell-pro2', price: 199, originalPrice: 249, discount: 20, description: 'HD video doorbell with head-to-toe view.', images: JSON.stringify(['https://images.unsplash.com/photo-1558002038-1091a16627a3?w=500']), specifications: JSON.stringify({ 'Resolution': '1536p', 'Field': 'Head-to-toe', 'WiFi': 'Dual-band', 'Power': 'Hardwired' }), rating: 4.5, reviewCount: 3210, inStock: true, stock: 80, seller: 'Ring', categorySlug: 'home-kitchen', featured: false, flashSale: true },
    { name: 'Eufy Security Camera', slug: 'eufy-security-camera', price: 129, originalPrice: 169, discount: 24, description: '2K security camera with night vision.', images: JSON.stringify(['https://images.unsplash.com/photo-1558002038-1091a16627a3?w=500']), specifications: JSON.stringify({ 'Resolution': '2K', 'Night Vision': 'Color', 'Storage': 'Local', 'AI': 'Human detection' }), rating: 4.4, reviewCount: 1876, inStock: true, stock: 100, seller: 'Eufy', categorySlug: 'home-kitchen', featured: false, flashSale: true },
    
    // More Beauty
    { name: 'Dyson Airwrap Complete', slug: 'dyson-airwrap-complete', price: 599, originalPrice: 699, discount: 14, description: 'Complete hair styling set with multiple barrels.', images: JSON.stringify(['https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500']), specifications: JSON.stringify({ 'Attachments': '6', 'Heat': '150°C', 'Motor': 'V9', 'Cord': '2.8m' }), rating: 4.6, reviewCount: 4532, inStock: true, stock: 45, seller: 'Dyson', categorySlug: 'beauty', featured: true, flashSale: true },
    { name: 'Ghd Gold Styler', slug: 'ghd-gold-styler', price: 249, originalPrice: 329, discount: 24, description: 'Premium flat iron with ceramic plates.', images: JSON.stringify(['https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500']), specifications: JSON.stringify({ 'Plates': 'Gold ceramic', 'Heat': '365°F', 'Technology': 'Predictive', 'Auto-off': 'Yes' }), rating: 4.7, reviewCount: 3210, inStock: true, stock: 50, seller: 'ghd', categorySlug: 'beauty', featured: false, flashSale: true },
    { name: 'T3 Featherweight Luxe', slug: 't3-featherweight-luxe', price: 279, originalPrice: 379, discount: 26, description: 'Ionic hair dryer for smooth results.', images: JSON.stringify(['https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500']), specifications: JSON.stringify({ 'Technology': 'Ionic', 'Heat': '3 settings', 'Speed': '2', 'Cool': 'Button' }), rating: 4.5, reviewCount: 1234, inStock: true, stock: 40, seller: 'T3', categorySlug: 'beauty', featured: false, flashSale: true },
    { name: 'La Roche-Posay Toleriane', slug: 'la-roche-toleriane', price: 19, originalPrice: 25, discount: 24, description: 'Soothing facial moisturizer.', images: JSON.stringify(['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500']), specifications: JSON.stringify({ 'Size': '50ml', 'Skin': 'Sensitive', 'Hydration': 'Rich', 'Fragrance': 'Free' }), rating: 4.5, reviewCount: 3210, inStock: true, stock: 200, seller: 'La Roche-Posay', categorySlug: 'beauty', featured: false, flashSale: true },
    { name: 'Vichy Mineral 89', slug: 'vichy-mineral-89', price: 22, originalPrice: 28, discount: 21, description: 'Hyaluronic acid booster serum.', images: JSON.stringify(['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500']), specifications: JSON.stringify({ 'Size': '50ml', 'Key': 'Mineral 89', 'HA': 'Yes', 'Skin': 'All types' }), rating: 4.5, reviewCount: 1876, inStock: true, stock: 150, seller: 'Vichy', categorySlug: 'beauty', featured: false, flashSale: true },
    { name: 'Bioderma Sensibio H2O', slug: 'bioderma-sensibio', price: 15, originalPrice: 19, discount: 21, description: 'Micellar water for sensitive skin.', images: JSON.stringify(['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500']), specifications: JSON.stringify({ 'Size': '500ml', 'Use': 'Makeup remover', 'Skin': 'Sensitive', 'Type': 'Micellar' }), rating: 4.6, reviewCount: 5432, inStock: true, stock: 300, seller: 'Bioderma', categorySlug: 'beauty', featured: false, flashSale: false },
    { name: 'Corsx Snail Mucin', slug: 'cosrx-snail-mucin', price: 18, originalPrice: 24, discount: 25, description: 'Snail secretion filtrate essence.', images: JSON.stringify(['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500']), specifications: JSON.stringify({ 'Size': '100ml', 'Key': '96% Snail Mucin', 'Skin': 'All types', 'K-beauty': 'Yes' }), rating: 4.6, reviewCount: 6543, inStock: true, stock: 400, seller: 'COSRX', categorySlug: 'beauty', featured: true, flashSale: true },
    { name: 'Laneige Water Bank Cream', slug: 'laneige-water-bank', price: 38, originalPrice: 48, discount: 21, description: 'Hydrating moisturizer with hyaluronic acid.', images: JSON.stringify(['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500']), specifications: JSON.stringify({ 'Size': '50ml', 'Key': 'Blue Hyaluronic', 'Skin': 'Dry', 'K-beauty': 'Yes' }), rating: 4.5, reviewCount: 2341, inStock: true, stock: 150, seller: 'Laneige', categorySlug: 'beauty', featured: false, flashSale: true },
    
    // More Sports
    { name: 'Garmin Forerunner 265', slug: 'garmin-forerunner-265', price: 499, originalPrice: 599, discount: 17, description: 'GPS running watch with AMOLED display.', images: JSON.stringify(['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500']), specifications: JSON.stringify({ 'Display': 'AMOLED', 'Battery': '15 days', 'GPS': 'Multi-band', 'Training': 'Advanced' }), rating: 4.8, reviewCount: 543, inStock: true, stock: 40, seller: 'Garmin', categorySlug: 'sports', featured: true, flashSale: true },
    { name: 'Polar Grit X Pro', slug: 'polar-grit-x-pro', price: 449, originalPrice: 549, discount: 18, description: 'Outdoor multisport watch with maps.', images: JSON.stringify(['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500']), specifications: JSON.stringify({ 'Battery': '40 hours', 'Maps': 'Offline', 'Sports': '80+', 'Waterproof': '100m' }), rating: 4.6, reviewCount: 321, inStock: true, stock: 30, seller: 'Polar', categorySlug: 'sports', featured: false, flashSale: true },
    { name: 'Suunto 9 Peak Pro', slug: 'suunto-9-peak-pro', price: 499, originalPrice: 629, discount: 21, description: 'Premium GPS watch with long battery.', images: JSON.stringify(['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500']), specifications: JSON.stringify({ 'Battery': '170 hours', 'GPS': 'Accuracy', 'Materials': 'Titanium', 'Waterproof': '100m' }), rating: 4.6, reviewCount: 234, inStock: true, stock: 25, seller: 'Suunto', categorySlug: 'sports', featured: false, flashSale: true },
    { name: 'Peloton Bike+', slug: 'peloton-bike-plus', price: 2495, originalPrice: 2795, discount: 11, description: 'Connected exercise bike with rotating screen.', images: JSON.stringify(['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500']), specifications: JSON.stringify({ 'Screen': '23.8" HD', 'Speakers': '2x10W', 'Camera': 'Yes', 'Membership': 'Included' }), rating: 4.7, reviewCount: 876, inStock: true, stock: 10, seller: 'Peloton', categorySlug: 'sports', featured: true, flashSale: false },
    { name: 'NordicTrack s22i Studio Cycle', slug: 'nordictrack-s22i', price: 1999, originalPrice: 2499, discount: 20, description: 'Smart cycle with iFit training.', images: JSON.stringify(['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500']), specifications: JSON.stringify({ 'Screen': '22" Touch', 'Incline': '20%', 'Decline': '10%', 'Speakers': 'Yes' }), rating: 4.5, reviewCount: 543, inStock: true, stock: 15, seller: 'NordicTrack', categorySlug: 'sports', featured: false, flashSale: true },
    { name: 'Hydrow Rower', slug: 'hydrow-rower', price: 2495, originalPrice: 2995, discount: 17, description: 'Live Outdoor Reality rowing machine.', images: JSON.stringify(['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500']), specifications: JSON.stringify({ 'Screen': '22" Touch', 'Drive': 'Magnetic', 'Noise': 'Quiet', 'Live': 'Rowing' }), rating: 4.6, reviewCount: 321, inStock: true, stock: 10, seller: 'Hydrow', categorySlug: 'sports', featured: false, flashSale: true },
    { name: 'Tonal Home Gym', slug: 'tonal-home-gym', price: 3495, originalPrice: 4495, discount: 22, description: 'Smart home gym with AI coaching.', images: JSON.stringify(['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500']), specifications: JSON.stringify({ 'Resistance': '200 lbs', 'Screen': '24" Touch', 'AI': 'Coach', 'Mount': 'Wall' }), rating: 4.7, reviewCount: 234, inStock: true, stock: 5, seller: 'Tonal', categorySlug: 'sports', featured: true, flashSale: true },
    { name: 'Tempo Studio', slug: 'tempo-studio', price: 1495, originalPrice: 1995, discount: 25, description: 'AI-powered home gym with weights.', images: JSON.stringify(['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500']), specifications: JSON.stringify({ 'Weights': 'Smart', 'Screen': '42" Touch', 'AI': 'Form feedback', 'Camera': '3D' }), rating: 4.5, reviewCount: 432, inStock: true, stock: 10, seller: 'Tempo', categorySlug: 'sports', featured: false, flashSale: true },
    { name: 'Theragun PRO', slug: 'theragun-pro', price: 599, originalPrice: 749, discount: 20, description: 'Professional percussion therapy device.', images: JSON.stringify(['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=500']), specifications: JSON.stringify({ 'Speed': '2400 RPM', 'Force': '60 lbs', 'Battery': '2.5 hours', 'Attachments': '6' }), rating: 4.7, reviewCount: 876, inStock: true, stock: 30, seller: 'Theragun', categorySlug: 'sports', featured: false, flashSale: true },
    { name: 'Hypervolt 2 Pro', slug: 'hypervolt-2-pro', price: 349, originalPrice: 449, discount: 22, description: 'Quiet percussion massage gun.', images: JSON.stringify(['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=500']), specifications: JSON.stringify({ 'Speed': '3 speeds', 'Weight': '2.2 lbs', 'Battery': '3 hours', 'Quieter': '60%' }), rating: 4.6, reviewCount: 1234, inStock: true, stock: 50, seller: 'Hyperice', categorySlug: 'sports', featured: false, flashSale: false },
  ];

  let created = 0;
  for (const product of products) {
    const existingProduct = await prisma.product.findUnique({ where: { slug: product.slug } });
    if (!existingProduct) {
      const categoryId = categoryMap[product.categorySlug];
      if (categoryId) {
        await prisma.product.create({
          data: {
            name: product.name,
            slug: product.slug,
            price: product.price,
            originalPrice: product.originalPrice,
            discount: product.discount,
            description: product.description,
            images: product.images,
            specifications: product.specifications,
            rating: product.rating,
            reviewCount: product.reviewCount,
            inStock: product.inStock,
            stock: product.stock,
            seller: product.seller,
            featured: product.featured,
            flashSale: product.flashSale,
            categoryId: categoryId,
          },
        });
        console.log('✅ Product created:', product.name);
        created++;
      }
    }
  }

  console.log(`🌱 Added ${created} more products!`);
}

main()
  .catch((e) => {
    console.error('❌ Failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
